<a href="https://colab.research.google.com/github/Savi1234gaba/data/blob/main/N2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np # import the numpy library and give it the alias 'np'

# Create a 2 D Array
arravali = np.array(np.random.randint(10,45,(8,2)))
print(f"The defined array is \n{arravali}")
print(f" \n The shape of the array is {arravali}")

The defined array is 
[[16 14]
 [40 34]
 [20 30]
 [37 38]
 [12 41]
 [36 20]
 [27 24]
 [11 14]]
 
 The shape of the array is [[16 14]
 [40 34]
 [20 30]
 [37 38]
 [12 41]
 [36 20]
 [27 24]
 [11 14]]


In [ ]:
# Storing the transpose in another matrix object
nilgiri =np.transpose(arravali)
print(f"The transpose of the array is \n{nilgiri}")
print(f" \n The shape of the array is {nilgiri.shape}")

The transpose of the array is 
[[16 40 20 37 12 36 27 11]
 [14 34 30 38 41 20 24 14]]
 
 The shape of the array is (2, 8)


In [ ]:
# 3D Array
random_3D_array = np.array(np.random.randint(10,45,(3,2,4)))
print(f"The defined array is \n{random_3D_array}")
print(f" \n The shape of the array is {random_3D_array.shape}")

The defined array is 
[[[43 11 40 38]
  [43 12 41 14]]

 [[35 10 28 36]
  [27 20 43 15]]

 [[41 21 35 30]
  [30 26 16 12]]]
 
 The shape of the array is (3, 2, 4)


In [ ]:
# 3D Array
random_3D_array = np.array(np.random.randint(10,45,(3,2,4)))
print(f"The defined array is \n{random_3D_array}")
print(f" \n The shape of the array is {random_3D_array.shape}")

The defined array is 
[[[37 40 40 22]
  [30 20 38 18]]

 [[42 20 12 29]
  [43 25 40 39]]

 [[43 40 23 33]
  [30 18 14 34]]]
 
 The shape of the array is (3, 2, 4)


In [ ]:
# Now we can reshape this to 1-D,2-D or 3-D array
new_shape = (2,6,2)
# Replacing random_cohort with random_3D_array as it was likely the variable intended to be reshaped
reshaped_random_cohort = np.reshape(random_3D_array,new_shape)
print(f"The reshaped array is \n{reshaped_random_cohort}")
print(f" \n The shape of the array is {reshaped_random_cohort.shape}")

The reshaped array is 
[[[37 40]
  [40 22]
  [30 20]
  [38 18]
  [42 20]
  [12 29]]

 [[43 25]
  [40 39]
  [43 40]
  [23 33]
  [30 18]
  [14 34]]]
 
 The shape of the array is (2, 6, 2)


In [ ]:
# Create a three-dimensional array
random_3D_cohort = np.array(np.random.randint(10,45,(3,6,2)))
print(f"The defined array is \n{random_3D_cohort}")
print(f" \n The shape of the array is (random_3D_cohort.shape)")

The defined array is 
[[[26 19]
  [33 40]
  [27 29]
  [11 39]
  [25 20]
  [35 17]]

 [[40 28]
  [15 26]
  [24 18]
  [40 16]
  [26 40]
  [35 36]]

 [[36 10]
  [34 44]
  [26 33]
  [26 34]
  [36 24]
  [30 21]]]
 
 The shape of the array is (random_3D_cohort.shape)


In [ ]:
# Resize the created 3D array
new_shape = (2,3,6)
resized_random_3D_cohort = np.resize(random_3D_cohort,new_shape)
print(f"The resized array is \n{resized_random_3D_cohort}")
print(f" \n The shape of the array is {resized_random_3D_cohort.shape}")

The resized array is 
[[[26 19 33 40 27 29]
  [11 39 25 20 35 17]
  [40 28 15 26 24 18]]

 [[40 16 26 40 35 36]
  [36 10 34 44 26 33]
  [26 34 36 24 30 21]]]
 
 The shape of the array is (2, 3, 6)


In [ ]:
random_3D_cohort.resize(new_shape)

random_3D_cohort

array([[[26, 19, 33, 40, 27, 29],
        [11, 39, 25, 20, 35, 17],
        [40, 28, 15, 26, 24, 18]],

       [[40, 16, 26, 40, 35, 36],
        [36, 10, 34, 44, 26, 33],
        [26, 34, 36, 24, 30, 21]]])

In [ ]:
# Initialize a 3D array
random_3D_cohort = np.array(np.random.randint(10,45,(2,4,6)))
print(f"The defined array is \n{random_3D_cohort}")
print(f" \n The shape of the array is {random_3D_cohort.shape}")

The defined array is 
[[[19 26 38 41 34 21]
  [19 26 41 30 27 13]
  [19 42 27 20 10 32]
  [15 40 35 40 37 13]]

 [[13 12 37 11 39 25]
  [36 14 24 32 19 14]
  [36 44 14 35 14 25]
  [34 28 34 27 29 40]]]
 
 The shape of the array is (2, 4, 6)


In [ ]:
# Flatten the 3d array
random_3D_cohort.flatten()

array([19, 26, 38, 41, 34, 21, 19, 26, 41, 30, 27, 13, 19, 42, 27, 20, 10,
       32, 15, 40, 35, 40, 37, 13, 13, 12, 37, 11, 39, 25, 36, 14, 24, 32,
       19, 14, 36, 44, 14, 35, 14, 25, 34, 28, 34, 27, 29, 40])

In [ ]:
# Flattens the array in row-major order with 'C'
random_3D_cohort.flatten(order='F')

array([19, 13, 19, 36, 19, 36, 15, 34, 26, 12, 26, 14, 42, 44, 40, 28, 38,
       37, 41, 24, 27, 14, 35, 34, 41, 11, 30, 32, 20, 35, 40, 27, 34, 39,
       27, 19, 10, 14, 37, 29, 21, 25, 13, 14, 32, 25, 13, 40])

In [ ]:
import numpy as np
a = np.random.randint(10, 45, size=(2, 3, 4))   # Axis 0 - 2 ; Axis 1- 3 ; Axis 2 - 4
print(a)
print(a.shape)

[[[29 17 41 16]
  [39 13 34 41]
  [11 43 12 40]]

 [[31 19 32 10]
  [10 22 39 14]
  [32 10 30 26]]]
(2, 3, 4)


In [ ]:
# Insert along axis = 0
np.insert(a,1,100,axis=0)

array([[[ 29,  17,  41,  16],
        [ 39,  13,  34,  41],
        [ 11,  43,  12,  40]],

       [[100, 100, 100, 100],
        [100, 100, 100, 100],
        [100, 100, 100, 100]],

       [[ 31,  19,  32,  10],
        [ 10,  22,  39,  14],
        [ 32,  10,  30,  26]]])

In [ ]:
# Insert along axis = 1
np.insert(a,0,50,axis=1)


array([[[50, 50, 50, 50],
        [29, 17, 41, 16],
        [39, 13, 34, 41],
        [11, 43, 12, 40]],

       [[50, 50, 50, 50],
        [31, 19, 32, 10],
        [10, 22, 39, 14],
        [32, 10, 30, 26]]])

In [ ]:
# Insert along axis = 2
np.insert(a,0,200,axis=2)

array([[[200,  29,  17,  41,  16],
        [200,  39,  13,  34,  41],
        [200,  11,  43,  12,  40]],

       [[200,  31,  19,  32,  10],
        [200,  10,  22,  39,  14],
        [200,  32,  10,  30,  26]]])

In [ ]:
# Append a value to the array. It flattens the array and append -99 to the end
np.append(a,50)

array([29, 17, 41, 16, 39, 13, 34, 41, 11, 43, 12, 40, 31, 19, 32, 10, 10,
       22, 39, 14, 32, 10, 30, 26, 50])

In [ ]:
# Fix the axis other than axis of appending
import numpy as np
b = np.random.rand(2,6).reshape(2,3,2)  # Changed shape to (2,3,2) or (2,2,3) or any other shape with total elements 12
print(b)


[[[0.1822896  0.10174761]
  [0.98931743 0.17388288]
  [0.74029333 0.01462889]]

 [[0.20905818 0.81153636]
  [0.66825377 0.35094933]
  [0.43491703 0.08507363]]]


In [ ]:
print(a)
print(a.shape)

[[[29 17 41 16]
  [39 13 34 41]
  [11 43 12 40]]

 [[31 19 32 10]
  [10 22 39 14]
  [32 10 30 26]]]
(2, 3, 4)


In [ ]:
a = np.random.randint(2, 6, size=(2, 3, 3))  # Corrected syntax
print(a)
print(a.shape)

[[[3 5 2]
  [5 2 5]
  [4 4 3]]

 [[5 5 5]
  [4 3 3]
  [5 5 2]]]
(2, 3, 3)


In [ ]:
# Delete along axis=0
np.delete(a,(0),axis = 0)

array([[[5, 5, 5],
        [4, 3, 3],
        [5, 5, 2]]])

In [ ]:
# Delete along axis=1
np.delete(a,(0,2),axis = 1)

array([[[5, 2, 5]],

       [[4, 3, 3]]])

In [ ]:
a

array([[[3, 5, 2],
        [5, 2, 5],
        [4, 4, 3]],

       [[5, 5, 5],
        [4, 3, 3],
        [5, 5, 2]]])

In [ ]:
# Delete along axis=2
np.delete(a,(0,1),axis = 2)

array([[[2],
        [5],
        [3]],

       [[5],
        [3],
        [2]]])

In [ ]:
#Initialized array
a = np.random.randint(2,20,(2,3,3))
print(a)
print(a.shape)

[[[16 12 15]
  [ 7 10  3]
  [ 5 16 16]]

 [[16 12  7]
  [14  5  7]
  [ 3 17 18]]]
(2, 3, 3)


In [ ]:
np.unique(a)

array([ 3,  5,  7, 10, 12, 14, 15, 16, 17, 18])

In [ ]:
# return_counts= True
np.unique(a,return_counts=True) # Returns tuple


(array([ 3,  5,  7, 10, 12, 14, 15, 16, 17, 18]),
 array([2, 2, 3, 1, 2, 1, 1, 4, 1, 1]))

In [ ]:
# return_index = True
np.unique(a,return_counts=True,return_index=True)

(array([ 3,  5,  7, 10, 12, 14, 15, 16, 17, 18]),
 array([ 5,  6,  3,  4,  1, 12,  2,  0, 16, 17]),
 array([2, 2, 3, 1, 2, 1, 1, 4, 1, 1]))

In [ ]:
# Let take an example of a list
a = [1,2,3]
b = a
b[0] = 10
print(b)
print(a)


[10, 2, 3]
[10, 2, 3]


In [ ]:
# Lets use the copy method
a = [1,2,3]
b = a.copy()
b[0] = 10
print(b)
print(a)

[10, 2, 3]
[1, 2, 3]


In [ ]:
a = np.array([2,34,12])
b = a
b[0] = -999
print(b)
print(a)

[-999   34   12]
[-999   34   12]


In [ ]:
a = np.array([2,34,12])
b = a.copy()
b[0] = -999
print(b)
print(a)

[-999   34   12]
[ 2 34 12]


In [ ]:
np.arange(3) + 5

array([5, 6, 7])

In [ ]:
np.ones((3,3)) + np.arange(3)

array([[1., 2., 3.],
       [1., 2., 3.],
       [1., 2., 3.]])

In [ ]:
np.arange(3).reshape((3,1)) + np.arange(3)

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4]])

In [ ]:
np.arange(3).reshape((3,1)) + np.arange(4)

array([[0, 1, 2, 3],
       [1, 2, 3, 4],
       [2, 3, 4, 5]])

In [ ]:
np.arange(2)

array([0, 1])

In [ ]:
# Example 2
a=np.random.randint(2,6,(2,4))
print(a)
b=np.random.randint(1,10,(2,2))
print(b)

[[2 4 2 4]
 [3 4 5 5]]
[[4 7]
 [2 9]]


In [ ]:
a = np.random.randint(2, 6, (2, 4)) # Changed 6(2,4) to 6, (2,4)
print(a)
b = np.random.randint(0, 5, (2, 4))
print(b)

[[4 5 5 5]
 [3 5 4 5]]
[[4 0 1 0]
 [4 4 4 4]]


In [ ]:
np.multiply(a,b)

array([[16,  0,  5,  0],
       [12, 20, 16, 20]])

In [ ]:
np.divide(a,b)

<ipython-input-60-c364992e28ce>:1: RuntimeWarning: divide by zero encountered in divide
  np.divide(a,b)


array([[1.  ,  inf, 5.  ,  inf],
       [0.75, 1.25, 1.  , 1.25]])

In [ ]:
a = np.random.randint(5, 9, size=(2,4))
print(a)

[[8 6 7 7]
 [8 7 8 7]]


In [ ]:
print(np.sum(a))
print(np.sum(a,axis=0))
print(np.sum(a,axis=1))

58
[16 13 15 14]
[28 30]


In [ ]:
# Calculate minimum
print(np.min(a)) # Minimum of the entire array
print(np.min(a,axis=0)) # Minimum across rows (along each column)
print(np.min(a,axis=1)) # Minimum across columns (along each row)

# The following line caused the error because 'a' is 2-dimensional and doesn't have an axis 2
# print(np.min(a,axis=2))

6
[8 6 7 7]
[6 7]


In [ ]:
# Sort the array
a=np.random.randint(0,20,(3,3))
print(a)

[[10  5  0]
 [ 4 14  7]
 [ 5 16  2]]


In [ ]:
print(np.sort(a,axis=0)) # Ascending

[[ 4  5  0]
 [ 5 14  2]
 [10 16  7]]


In [ ]:
print(np.sort(a,axis=1))

[[ 0  5 10]
 [ 4  7 14]
 [ 2  5 16]]


In [ ]:
sum(np.arange(3)*np.arange(3).transpose())

5